marked_points:
  source_image: events/calibration_main_frame.jpg
  frame_size:
  - 3840
  - 2160
  points:
  - idx: 1
    pixel:
    - 3426
    - 766
  - idx: 2
    pixel:
    - 3270
    - 753
  - idx: 3
    pixel:
    - 3104
    - 742
  - idx: 4
    pixel:
    - 2929
    - 740
  - idx: 5
    pixel:
    - 2743
    - 742
  - idx: 6
    pixel:
    - 2545
    - 740
  - idx: 7
    pixel:
    - 2345
    - 734
  - idx: 8
    pixel:
    - 2148
    - 738
  - idx: 9
    pixel:
    - 1952
    - 736
  - idx: 10
    pixel:
    - 1762
    - 745
  - idx: 11
    pixel:
    - 1583
    - 749
  - idx: 12
    pixel:
    - 1419
    - 757
  - idx: 13
    pixel:
    - 1254
    - 770
  - idx: 14
    pixel:
    - 1092
    - 781
  - idx: 15
    pixel:
    - 1470
    - 623
  - idx: 16
    pixel:
    - 1850
    - 598
  - idx: 17
    pixel:
    - 3179
    - 619
